// resources/react/components/BottomAuthHook.tsx
import { useLocalization } from '@laravilt/support/composables';
import AuthLinks from './AuthLinks';
import SocialLogin from './SocialLogin';
import type { AuthSocialProvider } from '../types';

export interface BottomAuthHookProps {
    forgotPasswordUrl?: string;
    registerUrl?: string;
    loginUrl?: string;
    canResetPassword?: boolean;
    canRegister?: boolean;
    canLogin?: boolean;
    mode?: 'login' | 'register' | 'forgot-password';
    socialProviders?: AuthSocialProvider[];
    socialRedirectUrl?: string;
}

export default function BottomAuthHook({
    forgotPasswordUrl,
    registerUrl,
    loginUrl,
    canResetPassword,
    canRegister,
    canLogin,
    mode,
    socialProviders,
    socialRedirectUrl,
}: BottomAuthHookProps) {
    const { trans } = useLocalization();

    return (
        <div className="space-y-6">
            {/* Auth Links */}
            <AuthLinks
                forgotPasswordUrl={forgotPasswordUrl}
                registerUrl={registerUrl}
                loginUrl={loginUrl}
                canResetPassword={canResetPassword}
                canRegister={canRegister}
                canLogin={canLogin}
                mode={mode}
            />

            {/* Social Login (with divider if there are providers) */}
            {socialProviders && socialProviders.length > 0 && (
                <div>
                    <div className="relative">
                        <div className="absolute inset-0 flex items-center">
                            <span className="w-full border-t"></span>
                        </div>
                        <div className="relative flex justify-center text-xs uppercase">
                            <span className="bg-background px-2 text-muted-foreground">
                                {trans('laravilt-auth::auth.social.or_continue_with')}
                            </span>
                        </div>
                    </div>

                    <div className="mt-4">
                        <SocialLogin providers={socialProviders} redirectUrl={socialRedirectUrl} />
                    </div>
                </div>
            )}
        </div>
    );
}

// resources/js/components/BottomAuthHook.vue
<script setup lang="ts">
import AuthLinks from './AuthLinks.vue';
import SocialLogin from './SocialLogin.vue';
import { useLocalization } from '@laravilt/support/composables';
import type { AuthSocialProvider } from '../types';

const { trans } = useLocalization();

const props = defineProps<{
    forgotPasswordUrl?: string;
    registerUrl?: string;
    loginUrl?: string;
    canResetPassword?: boolean;
    canRegister?: boolean;
    canLogin?: boolean;
    mode?: 'login' | 'register' | 'forgot-password';
    socialProviders?: AuthSocialProvider[];
    socialRedirectUrl?: string;
}>();
</script>

<template>
    <div class="space-y-6">
        <!-- Auth Links -->
        <AuthLinks
            :forgot-password-url="forgotPasswordUrl"
            :register-url="registerUrl"
            :login-url="loginUrl"
            :can-reset-password="canResetPassword"
            :can-register="canRegister"
            :can-login="canLogin"
            :mode="mode"
        />

        <!-- Social Login (with divider if there are providers) -->
        <div v-if="socialProviders && socialProviders.length > 0">
            <div class="relative">
                <div class="absolute inset-0 flex items-center">
                    <span class="w-full border-t"></span>
                </div>
                <div class="relative flex justify-center text-xs uppercase">
                    <span class="bg-background px-2 text-muted-foreground">{{
                        trans('laravilt-auth::auth.social.or_continue_with')
                    }}</span>
                </div>
            </div>

            <div class="mt-4">
                <SocialLogin
                    :providers="socialProviders"
                    :redirectUrl="socialRedirectUrl"
                />
            </div>
        </div>
    </div>
</template>
